/* Extra search terms per tool.
   The legacy search matched only name + description + category, so a nurse
   typing "kidney" found nothing and "sugar" found nothing. These are the lay
   words, abbreviations and eponyms people actually type under time pressure. */
export const SYNONYMS: Record<string, string[]> = {
  bmi: ['body mass index', 'obesity', 'overweight', 'weight status'],
  ibw: ['devine', 'ideal weight', 'drug dosing weight', 'ventilator weight'],
  bsa: ['mosteller', 'body surface', 'chemo dosing'],
  bmr: ['mifflin', 'resting energy', 'metabolism', 'calories'],
  tdee: ['calories', 'energy needs', 'diet', 'maintenance calories'],
  crcl: ['cockcroft', 'gault', 'kidney', 'renal dosing', 'creatinine clearance'],
  egfr: ['ckd', 'kidney', 'renal', 'gfr', 'ckd-epi', 'kidney function'],
  ag: ['anion gap', 'acidosis', 'dka', 'metabolic acidosis'],
  osm: ['osmolality', 'osmolar gap', 'toxic alcohol', 'ethylene glycol'],
  map: ['mean arterial pressure', 'perfusion', 'shock', 'sepsis target'],
  cca: ['calcium', 'albumin', 'hypocalcemia', 'hypercalcemia'],
  cna: ['sodium', 'hyponatremia', 'hyperglycemia', 'dka', 'hhs'],
  asa: ['anesthesia', 'preop', 'physical status', 'surgical risk'],
  rcri: ['lee index', 'cardiac risk', 'preop', 'perioperative'],
  caprini: ['vte', 'dvt risk', 'clot risk', 'thromboprophylaxis'],
  alvarado: ['appendicitis', 'mantrels', 'right iliac fossa', 'abdominal pain'],
  parkland: ['burns', 'fluid resuscitation', 'ringers', 'tbsa'],
  ron: ['rule of nines', 'burns', 'tbsa', 'wallace'],
  meldna: ['liver', 'cirrhosis', 'transplant', 'end stage liver'],
  wellsdvt: ['dvt', 'deep vein thrombosis', 'leg clot', 'wells'],
  wound: ['surgical site infection', 'ssi', 'cdc wound class'],
  ecog: ['performance status', 'karnofsky', 'who status', 'fitness for chemo'],
  chemodose: ['chemotherapy', 'mg/m2', 'body surface area dosing'],
  anc: ['neutropenia', 'neutrophil', 'febrile neutropenia', 'ctcae'],
  calvert: ['carboplatin', 'auc', 'chemotherapy dosing'],
  edd: ['due date', 'pregnancy', 'delivery date', 'naegele', 'lmp', 'ethiopian due date'],
  ga: ['gestational age', 'weeks pregnant', 'trimester', 'dating'],
  ovul: ['ovulation', 'fertile window', 'period', 'conception', 'trying to conceive'],
  fundal: ['symphysis fundal height', 'sfh', 'growth', 'iugr'],
  pwg: ['pregnancy weight gain', 'iom', 'antenatal weight'],
  bishop: ['induction', 'cervix', 'labour', 'labor induction'],
  apgar: ['newborn', 'neonate', 'birth score', 'resuscitation'],
  gtpal: ['obstetric history', 'gravida', 'para', 'parity'],
  ascvd: ['cardiovascular risk', 'pooled cohort', 'statin', 'heart risk', 'cholesterol'],
  bpclass: ['blood pressure', 'hypertension', 'acc aha', 'bp category'],
  qtc: ['qt interval', 'bazett', 'fridericia', 'torsades', 'ecg'],
  chadsvasc: ['atrial fibrillation', 'af', 'stroke risk', 'anticoagulation'],
  hasbled: ['bleeding risk', 'anticoagulation', 'warfarin', 'af'],
  shock: ['shock index', 'hemorrhage', 'trauma', 'occult shock'],
  hrzone: ['heart rate zones', 'karvonen', 'training', 'exercise'],
  peddose: ['pediatric dose', 'mg/kg', 'child dosing', 'paediatric'],
  pedfluid: ['holliday segar', '4-2-1', 'maintenance fluids', 'child fluids'],
  pedwt: ['apls', 'estimated weight', 'child weight', 'emergency weight'],
  pedbmi: ['child bmi', 'percentile', 'growth chart'],
  gcs: ['glasgow coma scale', 'consciousness', 'head injury', 'trauma'],
  qsofa: ['sepsis', 'quick sofa', 'infection screen'],
  sofa: ['organ failure', 'sepsis-3', 'icu score'],
  curb65: ['pneumonia', 'cap', 'community acquired pneumonia', 'admission'],
  wellspe: ['pulmonary embolism', 'pe', 'wells', 'ctpa', 'd-dimer'],
  pf: ['pao2 fio2', 'ards', 'berlin', 'oxygenation', 'p/f ratio'],
  hba1c: ['a1c', 'diabetes', 'sugar', 'blood glucose', 'eag'],
  homa: ['insulin resistance', 'homa-ir', 'metabolic syndrome'],
  fena: ['fractional excretion sodium', 'aki', 'prerenal', 'kidney injury'],
  hydrate: ['water intake', 'fluids', 'hydration', 'drinking water'],
  ranson: ['pancreatitis', 'severity', 'ranson criteria'],
  tnm: ['cancer staging', 'stage', 'ajcc', 'figo', 'oncology staging', 'tumour'],
  tnmcx: ['cervical cancer', 'figo 2018', 'cervix staging'],
  anthro: ['sam', 'malnutrition', 'z-score', 'muac', 'wasting', 'stunting', 'growth'],
  appetite: ['rutf', 'appetite test', 'otp', 'plumpy nut'],
  f75f100: ['f75', 'f100', 'therapeutic feed', 'stabilisation', 'sam feeding'],
  rutf: ['plumpy nut', 'sachet', 'otp ration', 'therapeutic food'],
  resomal: ['rehydration', 'sam diarrhoea', 'dehydration', 'ors'],
  wtgain: ['weight gain', 'g/kg/day', 'catch-up growth', 'rehabilitation'],
};
